Group4 initial second world changes
MSU-CSE491/cse_491_fall_2023 pull request #12
Opened 2023-09-24 17:32 UTC by hexactinal

2023-09-24 17:33 UTC, hexactinal commented
Can't seem to add a label on the right side, so we might not have label permissions.

2023-09-25 17:07 UTC, FergusonAJ commented
> Can't seem to add a label on the right side, so we might not have label permissions.

Good catch!
I gave all teams "Triage" access. Let me know if that's enough or not.

2023-10-07 22:55 UTC, amantham20 reviewed
Have to also sync changes from the main repo. :)

2023-10-07 22:55 UTC, amantham20 commented on .gitignore
I would .vscode/* be recommended instead.
similarly *.exe just to make

2023-10-07 22:56 UTC, amantham20 requested changes
Have to also sync changes from the main repo. :)

2023-10-08 17:37 UTC, hexactinal commented on .gitignore
I just removed my changes to the gitignore file since I think it already had exe and vscode editor files. Is this ready to merge now?

2023-10-08 20:00 UTC, amantham20 reviewed
add in 
<img width="301" alt="image" src="https://github.com/MSU-CSE491/cse_491_fall_2023/assets/48414198/3dbe2c0c-1e35-4bff-addb-ec556daee558">
 to ensure that main cmake picks the group4 main up

2023-10-08 20:05 UTC, amantham20 commented
1 more change 

the property for setting the character name has been changed to 
`world.AddAgent<cse491::TrashInterface>("Interface").SetProperty("symbol", '@');`

2023-10-08 20:17 UTC, amantham20 commented
<img width="360" alt="image" src="https://github.com/MSU-CSE491/cse_491_fall_2023/assets/48414198/60a3ed95-3274-4035-ab29-7c6687b5ac38">

I was able to get close to goal state but not on it not sure if this was the expected behavior

2023-10-10 22:55 UTC, amantham20 approved these changes
![image](https://github.com/MSU-CSE491/cse_491_fall_2023/assets/48414198/06f4791b-7cdf-4500-9fb0-821ec327a514)

2023-10-11 17:31 UTC, mercere99 commented on CMakeLists.txt
> +set(EXECUTABLES simple sfml_example group4_main)
The "group4_main" executable should be just "group4".

2023-10-11 17:32 UTC, mercere99 commented on source/Worlds/SecondWorld.hpp
> +    class SecondWorld : public cse491::MazeWorld {
Consider deriving directly from WorldBase.

2023-10-11 17:33 UTC, mercere99 commented on source/Worlds/SecondWorld.hpp
> +            cse491::MazeWorld();
Calling base class constructor can be done in initializer list.

2023-10-11 17:35 UTC, mercere99 commented on source/Worlds/SecondWorld.hpp
> +            cse491::MazeWorld();
(This current version will call the base class constructor twice)

2023-10-19 18:01 UTC, merged