Group 1 Wed Sept 27th checkin
MSU-CSE491/cse_491_fall_2023 pull request #21
Opened 2023-09-28 00:11 UTC by mdkdoc15

This PR will add the first external agent of group one. It tracks a path using A* to a given coordinate. 
`auto my_agent = dynamic_cast<cse491::walle::matt_k_first_agent *>(agent);
  my_agent->set_word(&world);
  my_agent->set_goal_position(cse491::GridPosition(1, 8));
  my_agent->SetPosition(3, 1);`
  
  Will create an agent that goes from position (3,1) to (1,8) While avoiding walls and other un-walkable areas defined by the world. 
  
  Future changes:

1.   Assert goal position and world pointer are not Null to avoid seg faults
2.  Refector agent to have a better name than matt_k_first agent
3. Add additional agent with user defined path to follow
4. Add capability of agent to track moving target.

2023-09-28 21:59 UTC, Kanakmk approved these changes
Reviewed and everything checks out!!

2023-10-10 16:46 UTC, FergusonAJ requested changes
Overall the changes look good. This PR adds A* pathfinding and an agent that uses it to move between multiple waypoints. 

Two things we should change before merging: 
1. Switch the `.h` files to `.hpp` to keep things consistent
2. Similarly, changing `shortest_path` to be more consistent with the rest of the methods. Maybe something like `GetShortestPath` or `FindShortestPath`?

2023-10-10 16:46 UTC, FergusonAJ commented on Group 1 - README.md
Glad you added documentation! 
At some point we should probably convert some of it to in-file doxygen comments, but this is great for now!

2023-10-10 16:46 UTC, FergusonAJ commented on source/Agents/AStarAgent.h
We should figure out what we want to put in the comment block at the top of each file eventually.

2023-10-10 16:46 UTC, FergusonAJ commented on source/Agents/AgentLibary.h
Should we rename this to be a `.hpp` like the rest of the header files? (Same for AgentLibrary, I missed it there)

2023-10-10 16:46 UTC, FergusonAJ commented on source/core/WorldBase.hpp
I think this looks good.
There is an argument that maybe we should make `IsWalkable` pure virtual, but I think this is fine for now. 

It would be nice if `shortest_path` was in WorldGrid, but I guess it needs access to `IsWalkable`. 
We should probably switch it to `GetShortestPath` or something to match the style of the rest of the code.

2023-10-10 22:11 UTC, FergusonAJ requested changes
Went through in more detail this time. 
There is one critical change left: to remove a circular include. Instructions for how to do that are in one of the review comments. 

Thanks for making the other changes earlier!

2023-10-10 22:11 UTC, FergusonAJ commented on Group 1 - README.md
We should move this to `docs`, I missed that last time.

2023-10-10 22:11 UTC, FergusonAJ commented on source/Agents/AgentLibary.hpp
The include of WorldBase is unnecessary and creates a circular include. This prevents the code from compiling on my machine. We should remove it.

2023-10-11 17:53 UTC, mercere99 commented on source/Agents/AStarAgent.hpp
> +                    path = world->ShortestPath(GetPosition(), goal_position);
Needs to know which agent is asking for the shortest path.

2023-10-19 19:33 UTC, merged